language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

node_js:
  - "stable"

before_script:
  - npm install -g bower
  - bower install
  - echo 'after bower'

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev
