language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

node_js:
  - "stable"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev
